lms/urls.py
from django.contrib import admin
from django.urls import path, include

from core_lms.views import index

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('__debug__/', include('debug_toolbar.urls'))
]

teachers/urls.py
from django.urls import path

from teachers.views import get_teachers, create_teacher, update_teacher, delete_teacher

app_name = 'teachers'


urlpatterns = [
    path('', get_teachers, name='list_teachers'),
    path('create', create_teacher, name='create_teachers'),
    path('update/<int:id>', update_teacher, name='edit_teachers'),
    path('delete/<int:id>', delete_teacher, name='delete_teachers')

]

teachers/models.py
from django.db import models
from faker import Faker
import random


class Teacher(models.Model):
    first_name = models.CharField(max_length=64, null=False)
    last_name = models.CharField(max_length=64, null=False)
    it_experience = models.IntegerField(null=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    birth_date = models.DateTimeField(null=True, blank=True)
    phone_number = models.CharField(max_length=16, null=True, blank=True)
    inn = models.PositiveIntegerField(unique=True, null=True)
    group = models.ForeignKey(
        to='groups.Group',
        null=True,
        on_delete=models.SET_NULL,
        related_name='teachers'
    )

    @classmethod
    def get_teachers(cls, count):
        fake = Faker()
        for _ in range(count):
            t = Teacher()
            t.first_name = fake.first_name()
            t.last_name = fake.last_name()
            t.email = fake.email()
            t.phone_number = fake.phone_number()
            t.it_experience = random.randint(1, 10)
            t.birth_date = fake.date_time()

            t.save()

    def __str__(self):
        return f'Teacher({self.id}) {self.first_name} ' \
               f'{self.last_name} (IT experience {self.it_experience} y.)' \
               f'{self.email},{self.phone_number},{self.birth_date}'

    @property
    def name(self):
        return f'{self.first_name} {self.last_name}'

teachers/forms.py
import re

import django_filters
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from teachers.models import Teacher


class TeacherFilter(django_filters.FilterSet):
    class Meta:
        model = Teacher
        fields = ['first_name', 'last_name', 'it_experience']


class TeacherBaseForm(ModelForm):
    class Meta:
        model = Teacher
        fields = ['first_name', 'last_name', 'it_experience', 'email', 'birth_date', 'phone_number', 'inn']

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        if not re.match(r'(\+\d\d?)?\(\d{3}\)(\d-?){7}$', phone_number):
            raise ValidationError('Phone number should be in'
                                  'format +1(121)323-32-23')
        return self.cleaned_data['phone_number']

    def clean_email(self):
        ignore_email = ['yandex.ua', 'vk.com']
        email = self.cleaned_data['email']
        if not re.search(r'@(yandex\.ua|vk\.com)$', email):
            return self.cleaned_data['email']
        else:
            raise ValidationError(f'Email should not be in {ignore_email}')


class TeacherCreateForm(TeacherBaseForm):
    pass


class TeacherUpdateForm(TeacherBaseForm):
    class Meta:
        model = Teacher
        fields = '__all__'
        exclude = ['it_experience']

teachers/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404  # noqa
from django.urls import reverse

from teachers.forms import TeacherCreateForm, TeacherUpdateForm, TeacherFilter
from teachers.models import Teacher


def get_teachers(request):
    qs = Teacher.objects.all()
    qs = qs.order_by('-id')
    teachers_filter = TeacherFilter(data=request.GET, queryset=qs)

    return render(request, 'teachers/list_teachers.html', {
        'filter': teachers_filter
    })


def create_teacher(request):
    if request.method == 'POST':
        form = TeacherCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('teachers:list_teachers'))
    else:
        form = TeacherCreateForm()

    return render(request, 'teachers/create_teacher.html', {'form': form})


def update_teacher(request, id):
    teacher = get_object_or_404(Teacher, id=id)

    if request.method == 'POST':
        form = TeacherUpdateForm(request.POST, instance=teacher)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('teachers:list_teachers'))
    else:
        form = TeacherUpdateForm(instance=teacher)

    return render(request, 'teachers/edit_teacher.html', {'form': form})


def delete_teacher(request, id):
    teacher = get_object_or_404(Teacher, id=id)
    if request.method == 'POST':
        teacher.delete()
        return HttpResponseRedirect(reverse('teachers:list_teachers'))
    return render(
        request,
        'teachers/delete_teachers.html',
        {'teacher': teacher
         }
    )

teachers/templates/teachers/create_teacher.html
{% extends '__base.html' %}
{% load crispy_forms_tags %}
{% block title %} Create teacher{% endblock %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <p>
            <button type="submit">Create Teacher</button>
        </p>
    </form>
{% endblock %}

teachers/templates/teachers/delete_teachers.html
{% extends '__base.html' %}
{% block title %}Delete teacher{% endblock %}
{% block main %}
    <form method="post">
        {% csrf_token %}
        <p> Do you want to delete teacher {{ teacher.name }} ?<p>
            <button class="btn btn-danger" type="submit">Delete</button>
             <a class="btn btn-info" href="{% url 'teachers:list_teachers' %}">Cancel</a>
        </p>
    </form>
{% endblock %}

teachers/templates/teachers/edit_teacher.html
{% extends '__base.html' %}
{% load crispy_forms_tags %}
{% block title %}Edit teacher{% endblock %}
{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <p>
            <button type="submit">Update Teacher</button>
        </p>
    </form>
{% endblock %}

teachers/templates/teachers/list_teachers.html
{% extends '__base.html' %}
{% block title %}View teachers{% endblock %}
{% load crispy_forms_tags %}
{% block main %}
    <form>
        <p>Search teachers</p>
        {{ filter.form|crispy }}
        <p>
            <button class="btn btn-light text-info" type="submit">Search</button>
        </p>
    </form>
    <br>
    <a class="btn btn-light text-primary" href="{% url 'teachers:create_teachers' %}">Add new teacher</a>
    <br>
    <p> </p>
    <table class="table table-bordered border-primary">
           <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>INN</th>
        <th>Email</th>
        <th></th>
    </tr>

    {% for teacher in filter.qs|slice:":20" %}
        <tr>
            <td>{{ teacher.first_name|capfirst }}
            <td>{{ teacher.last_name|title }}</td>
            <td>{{ teacher.inn }}</td>
            <td>{{ teacher.email }}</td>
            <td><a href="{% url 'teachers:edit_teachers' id=teacher.id %}">✎</a>
            <a href="{% url 'teachers:delete_teachers' id=teacher.id %}">␥</a></td>

        </tr>
    {% endfor %}
    </table>

{% endblock %}