lms/urls.py
from django.contrib import admin
from django.urls import path, include

from core_lms.views import index

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('__debug__/', include('debug_toolbar.urls'))
]

teachers/urls.py
from django.urls import path

from teachers.views import get_teachers, create_teacher, update_teacher, delete_teacher

app_name = 'teachers'


urlpatterns = [
    path('', get_teachers, name='list_teachers'),
    path('create', create_teacher, name='create_teachers'),
    path('update/<int:id>', update_teacher, name='edit_teachers'),
    path('delete/<int:id>', delete_teacher, name='delete_teachers')

]

templates/__base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <style type="text/css">

    </style>
</head>
<body>
    <p>
        {% include '__header_menu.html' %}
    </p>
    <div class="container">
    {% block main %}
        {% endblock %}
    </div>
</body>

</html>

templates/__header_menu.html
<!--<a class="btn btn-info" href="/">LMS</a><a class="btn btn-info" href="{% url 'teachers:list_teachers' %}">Teachers</a>-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid bg-primary">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand text-body " href="/">LMS</a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link active text-body " aria-current="page" href="{% url 'teachers:list_teachers' %}">Teachers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-body"  href="{% url 'list_students' %}">Students</a>
        </li>
<!--        <li class="nav-item">-->
<!--          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
<!--        </li>-->
<!--      </ul>-->
<!--      <form class="d-flex">-->
<!--        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
<!--        <button class="btn btn-outline-success" type="submit">Search</button>-->
<!--      </form>-->
      </ul>>
    </div>
  </div>
</nav>

templates/index.html
{%extends '_base.html'%}
{% block main %}
<h1>Welcome to LMS!</h1>
{% endblock %}